<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-D44L6FM" failures="1" tests="6" name="CustomerTest" time="9.308" errors="0" timestamp="2024-06-05T10:49:54 CST" skipped="3">
  <testcase classname="CustomerTest" name="customerJava" time="1.962"/>
  <testcase classname="CustomerTest" name="customerTestNG" time="1.398">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at CustomerTest.customerTestNG(CustomerTest.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at org.testng.internal.thread.graph.TestNGFutureTask.run(TestNGFutureTask.java:22)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- customerTestNG -->
  <testcase classname="CustomerTest" name="customerSelenium" time="1.586"/>
  <testcase classname="CustomerTest" name="customerTestNG" time="1.545">
    <skipped/>
  </testcase> <!-- customerTestNG -->
  <testcase classname="CustomerTest" name="customerTestNG" time="1.379">
    <skipped/>
  </testcase> <!-- customerTestNG -->
  <testcase classname="CustomerTest" name="customerTestNG" time="1.438">
    <skipped/>
  </testcase> <!-- customerTestNG -->
</testsuite> <!-- CustomerTest -->
